apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: otus3-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: arch.homework
      http:
        paths:
          - path: /user
            backend:
              serviceName: otus3-service
              servicePort: 9000
          - path: /user($|/)(.*)
            backend:
              serviceName: otus3-service
              servicePort: 9000