fullnameOverride: postgres
postgresqlUsername: user
postgresqlPassword: user
postgresqlDatabase: orders

service:
  type: NodePort
  port: 5432

persistence:
  enabled: true
  size: 1Gi

resources:
  requests:
    memory: 256Mi
    cpu: 250m