apiVersion: v1
kind: Service
metadata:
  name: otus3-service
spec:
  selector:
    app: otus3
  ports:
    - protocol: TCP
      port: 9000
      targetPort: container-port
      name: web
  type: NodePort