replicaCount: 1

fullnameOverride: "auth-app"

image: nitrodenov/otus:v5.2.11

deployment:
  app: otus5
  targetPort: container-port

service:
  type: NodePort
  port: 9000
  app: otus5
  targetPort: container-port