apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "auth-chart.fullname" . }}
  labels:
    {{- include "auth-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "auth-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
      labels:
        {{- include "auth-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image }}"
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "auth-chart.fullname" . }}-secret
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "auth-chart.fullname" . }}-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "auth-chart.fullname" . }}-secret
                  key: DB_PASSWORD
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ include "auth-chart.fullname" . }}-secret
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ include "auth-chart.fullname" . }}-secret
                  key: DB_PORT