{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "otus3.fullname" . }}-servicemonitor
  labels:
    app: {{ .Values.serviceMonitor.app }}
spec:
  jobLabel: {{ include "otus3.fullname" . }}
  namespaceSelector:
    matchNames:
      - "{{ $.Release.Namespace }}"
  selector:
    matchLabels:
      app: {{ .Values.serviceMonitor.app }}
  endpoints:
    - interval: 15s
      port: web
      path: /metrics
{{- end }}